# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ice/setup-makefiles.sh

PRODUCT_SOONG_NAMESPACES += \
    vendor/xiaomi/ice

PRODUCT_COPY_FILES += \
    vendor/xiaomi/ice/proprietary/vendor/bin/chipinfo:$(TARGET_COPY_OUT_VENDOR)/bin/chipinfo \
    vendor/xiaomi/ice/proprietary/vendor/bin/init.insmod.sh:$(TARGET_COPY_OUT_VENDOR)/bin/init.insmod.sh \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.ht120.mtc:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.ht120.mtc \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_00:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_00 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_03:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_03 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_10:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_10 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_11:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_11 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_12:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_12 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_13:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_13 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_14:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_14 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_15:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_15 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_16:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_16 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_17:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_17 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_18:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_18 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/.thermal_policy_19:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/.thermal_policy_19 \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/thermal.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/.tp/thermal.off.conf:$(TARGET_COPY_OUT_VENDOR)/etc/.tp/thermal.off.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/AbnormalDisplayLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AbnormalDisplayLog_dynamic.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/AudioLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/AudioLog_dynamic.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/MNL_Config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/MNL_Config.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/NOTICE_GPL.html.gz:$(TARGET_COPY_OUT_VENDOR)/etc/NOTICE_GPL.html.gz \
    vendor/xiaomi/ice/proprietary/vendor/etc/VideoLog_dynamic.xml:$(TARGET_COPY_OUT_VENDOR)/etc/VideoLog_dynamic.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/a2dp_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dp_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/a2dp_in_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/a2dp_in_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/aee-commit:$(TARGET_COPY_OUT_VENDOR)/etc/aee-commit \
    vendor/xiaomi/ice/proprietary/vendor/etc/aee-config:$(TARGET_COPY_OUT_VENDOR)/etc/aee-config \
    vendor/xiaomi/ice/proprietary/vendor/etc/apdb/APDB_MT6761_S01__W2222:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6761_S01__W2222 \
    vendor/xiaomi/ice/proprietary/vendor/etc/apdb/APDB_MT6761_S01__W2222_ENUM:$(TARGET_COPY_OUT_VENDOR)/etc/apdb/APDB_MT6761_S01__W2222_ENUM \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_device.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_device.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_effects.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_effects.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_em.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_em.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/BtInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/BtInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/BtInfo_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/HpImpedance_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/HpImpedance_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/HpImpedance_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/MicInfo_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/MicInfo_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/MicInfo_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackACF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackACF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackACF_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackDRC_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackDRC_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackHCF_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackHCF_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolAna_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolAna_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolDigi_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolDigi_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/PlaybackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Playback_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Playback_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamTreeView.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Playback_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Playback_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordFIR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordFIR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordFIR_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RecordVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RecordVol_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Record_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Record_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamTreeView.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Record_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Record_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RingbackVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RingbackVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/RingbackVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/RingbackVol_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SmartPa_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SmartPa_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SmartPa_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SoundEnhancement_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SoundEnhancement_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechEchoRef_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechEchoRef_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechMagiClarity_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechMagiClarity_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechNetwork_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechNetwork_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/SpeechVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/SpeechVol_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Speech_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Speech_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamTreeView.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Speech_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Speech_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/USBCall_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/USBCall_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBCall_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/USBDevice_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/USBDevice_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/USBDevice_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Ultrasound_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Ultrasound_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Ultrasound_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/UplinkConfiguration_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/UplinkConfiguration_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPDMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPDMNR_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPGeneral_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPGeneral_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPVolUI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVolUI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPVol_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPVol_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPVol_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIP_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIP_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamTreeView.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIP_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIP_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2DMNR_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2DMNR_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2General_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2General_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2General_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2UI_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2UI_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2_ParamTreeView.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamTreeView.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoIPv2_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoIPv2_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWDspAec_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWDspAec_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWDspAec_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWEngineFeature_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWEngineFeature_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWHwVad_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWHwVad_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWHwVad_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWMicSetting_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWMicSetting_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWVoiceCommand_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VoWVoiceCommand_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VolumeGainMapUL_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMapUL_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VolumeGainMap_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/VolumeGainMap_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Volume_AudioParam.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_AudioParam.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_param/Volume_ParamUnitDesc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_param/Volume_ParamUnitDesc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_policy.conf:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_policy_configuration_bluetooth_legacy_hal.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_configuration_bluetooth_legacy_hal.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/audio_policy_volumes.xml:$(TARGET_COPY_OUT_VENDOR)/etc/audio_policy_volumes.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/aurisys_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/aurisys_config_rv.xml:$(TARGET_COPY_OUT_VENDOR)/etc/aurisys_config_rv.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/bluetooth_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/bluetooth_offload_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/bluetooth_offload_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/cgroups.json:$(TARGET_COPY_OUT_VENDOR)/etc/cgroups.json \
    vendor/xiaomi/ice/proprietary/vendor/etc/cit_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/cit_config.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/default_pd_calibration.bin:$(TARGET_COPY_OUT_VENDOR)/etc/default_pd_calibration.bin \
    vendor/xiaomi/ice/proprietary/vendor/etc/default_volume_tables.xml:$(TARGET_COPY_OUT_VENDOR)/etc/default_volume_tables.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP01.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP01.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP02.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP02.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP09.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP09.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP12.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP12.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP17.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP17.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP18.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP18.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP20.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP20.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_OP236.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_OP236.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/ecc_list_preference.xml:$(TARGET_COPY_OUT_VENDOR)/etc/ecc_list_preference.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/factory.ini:$(TARGET_COPY_OUT_VENDOR)/etc/factory.ini \
    vendor/xiaomi/ice/proprietary/vendor/etc/fstb.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/fstb.cfg \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/agps_profiles_conf2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/agps_profiles_conf2.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_Mexico.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_ATnT_US.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_CT.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Claro_Peru.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Entel_Peru.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_KDDI.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SK_Telecom.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_SoftBank.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Sprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_T-Mobile_US.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM1.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Test_SIM2.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml:$(TARGET_COPY_OUT_VENDOR)/etc/gnss/carrier/agps_profiles_conf2_carrier_Verizon_Wireless.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/aee_aedv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/aee_aedv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.usb@1.2-service-mediatekv2.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/android.hardware.wifi.supplicant-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/android.hardware.wifi.supplicant-service.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/atci_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/atci_service.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/atcid.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/atcid.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/audiocmdservice_atci.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/audiocmdservice_atci.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/bootperf.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/bootperf.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/chipinfo_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/chipinfo_init.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/dmc_core.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/dmc_core.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/em_hidl_user.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/em_hidl_user.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/fuelgauged_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/fuelgauged_init.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/gsm0710muxd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/gsm0710muxd.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hostapd.android.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hostapd.android.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/factory_init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/factory_init.connectivity.common.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/factory_init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/factory_init.connectivity.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/factory_init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/factory_init.project.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/factory_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/factory_init.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.aee.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.aee.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.ago.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.ago.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.cgroup.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.cgroup.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.common.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.connectivity.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.modem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.modem.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.mt6761.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6761.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.mt6761.usb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.mt6761.usb.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.project.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init.sensor_1_0.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init.sensor_1_0.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/init_connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/init_connectivity.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.connectivity.common.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.connectivity.common.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.connectivity.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.connectivity.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.modem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.modem.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.project.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.project.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/meta_init.vendor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/meta_init.vendor.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/hw/multi_init.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/hw/multi_init.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.bip.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bip.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.bt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.bt_drv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.cccimdinit.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccimdinit.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.cccirpcd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.cccirpcd.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.connfem.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.connfem.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.fmradio_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fmradio_drv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.fpsgo.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.fpsgo.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.gps_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.gps_drv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.md_apps.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.md_apps.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.thermal.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.thermal_manager.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermal_manager.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.thermalloadalgod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.thermalloadalgod.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.volte_imcb.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imcb.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.volte_imsm_93.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_imsm_93.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.volte_md_status.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_md_status.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.volte_stack.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_stack.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.volte_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.volte_ua.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.wfca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wfca.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.wlan_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wlan_drv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.wmt_drv.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wmt_drv.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/init.wod.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/init.wod.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/ipsec_mon.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/ipsec_mon.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/lights-mtk-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/lights-mtk-lazy.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/loghidlvendorservice.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/loghidlvendorservice.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/md_monitor.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/md_monitor.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/microtrust.bp_kmsetkey_ca.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.bp_kmsetkey_ca.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/microtrust.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/microtrust.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/mtk_agpsd_p.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_agpsd_p.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/mtk_pkm_service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtk_pkm_service.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/mtklog.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtklog.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/mtkrild.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/mtkrild.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/muxreport.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/muxreport.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/netdagent.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/netdagent.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/networksetting.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/networksetting.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/vendor.xiaomi.hardware.mtdservice@1.2-service.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vendor.xiaomi.hardware.mtdservice@1.2-service.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/vibrator-mtk-lazy.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/vibrator-mtk-lazy.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/volte_rcs_ua.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/volte_rcs_ua.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/init/wlan_assistant.rc:$(TARGET_COPY_OUT_VENDOR)/etc/init/wlan_assistant.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootCA.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG2.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/DigiCertGlobalRootG3.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Entrust.net_Certification_Authority_2048.cer \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/EntrustRootCertificationAuthorityG2_root.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/EntrustRootCertificationAuthorityG2_root.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_PCA_G3_Root.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GeoTrust_Primary_CA_G2_ECC.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/GlobalSign_root_CA.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/GlobalSign_root_CA.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/LibertyGlobalEnterprise-Root-CA-G1.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/LibertyGlobalEnterprise-Root-CA-G1.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root-R3.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root-R3.cer \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/Root_CA_1003.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/USERTrustRSACertificationAuthority.crt:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/USERTrustRSACertificationAuthority.crt \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G4.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignClass3G5.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/VeriSignUniversalRootCertification.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/gold.cer:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/gold.cer \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ipsec.d/cacerts/thawte.der:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ipsec.d/cacerts/thawte.der \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/ssl/openssl.cnf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/ssl/openssl.cnf \
    vendor/xiaomi/ice/proprietary/vendor/etc/ipsec/strongswan.conf:$(TARGET_COPY_OUT_VENDOR)/etc/ipsec/strongswan.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_c2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_c2.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_google_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_audio.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_google_video_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_google_video_le.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_mediatek_audio.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_audio.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_mediatek_video.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_mediatek_video.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_codecs_performance.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_codecs_performance.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/media_profiles_V1_0.xml:$(TARGET_COPY_OUT_VENDOR)/etc/media_profiles_V1_0.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/mtk_omx_core.cfg:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_omx_core.cfg \
    vendor/xiaomi/ice/proprietary/vendor/etc/mtk_platform_codecs_config.xml:$(TARGET_COPY_OUT_VENDOR)/etc/mtk_platform_codecs_config.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/partition_permission.sh:$(TARGET_COPY_OUT_VENDOR)/etc/partition_permission.sh \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.audio.low_latency.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.audio.low_latency.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.bluetooth.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.bluetooth_le.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.bluetooth_le.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.camera.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.camera.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.faketouch.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.faketouch.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.location.gps.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.location.gps.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.microphone.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.microphone.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.opengles.aep.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.opengles.aep.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.sensor.accelerometer.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.accelerometer.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.sensor.light.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.light.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.sensor.proximity.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.proximity.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.sensor.stepcounter.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepcounter.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.sensor.stepdetector.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.sensor.stepdetector.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.telephony.gsm.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.gsm.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.telephony.ims.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.telephony.ims.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.distinct.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.jazzhand.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.touchscreen.multitouch.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.multitouch.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.touchscreen.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.touchscreen.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.usb.accessory.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.accessory.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.usb.host.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.usb.host.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.wifi.direct.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.direct.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.wifi.passpoint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.passpoint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.hardware.wifi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.hardware.wifi.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.software.ipsec_tunnels.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.ipsec_tunnels.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.software.midi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.midi.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.software.opengles.deqp.level.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.opengles.deqp.level.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/android.software.verified_boot.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/android.software.verified_boot.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/com.fingerprints.extension.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/com.fingerprints.extension.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/sku_c3sfg/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/sku_c3sfg/android.hardware.fingerprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/sku_c3sfin/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/sku_c3sfin/android.hardware.fingerprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/sku_c3sfinh/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/sku_c3sfinh/android.hardware.fingerprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/sku_c3sp/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/sku_c3sp/android.hardware.fingerprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/permissions/sku_c3sph/android.hardware.fingerprint.xml:$(TARGET_COPY_OUT_VENDOR)/etc/permissions/sku_c3sph/android.hardware.fingerprint.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/power_app_cfg.xml:$(TARGET_COPY_OUT_VENDOR)/etc/power_app_cfg.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/powercontable.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powercontable.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/powerscntbl.xml:$(TARGET_COPY_OUT_VENDOR)/etc/powerscntbl.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/public.libraries.txt:$(TARGET_COPY_OUT_VENDOR)/etc/public.libraries.txt \
    vendor/xiaomi/ice/proprietary/vendor/etc/qc.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qc.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/qc_Global.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qc_Global.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/qc_Global_2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qc_Global_2.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/qc_India.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qc_India.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/qc_India_2.xml:$(TARGET_COPY_OUT_VENDOR)/etc/qc_India_2.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/r_submix_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/r_submix_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/rcv_pb.wav:$(TARGET_COPY_OUT_VENDOR)/etc/rcv_pb.wav \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/PRC/ro.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/PRC/ro.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/PRC/rw.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/PRC/rw.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/ROW/ro.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/ROW/ro.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/ROW/rw.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/ROW/rw.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/default/ro.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/default/ro.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/rsc/default/rw.prop:$(TARGET_COPY_OUT_VENDOR)/etc/rsc/default/rw.prop \
    vendor/xiaomi/ice/proprietary/vendor/etc/seccomp_policy/mediacodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediacodec.policy \
    vendor/xiaomi/ice/proprietary/vendor/etc/seccomp_policy/mediaextractor.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaextractor.policy \
    vendor/xiaomi/ice/proprietary/vendor/etc/seccomp_policy/mediaswcodec.policy:$(TARGET_COPY_OUT_VENDOR)/etc/seccomp_policy/mediaswcodec.policy \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/01419da9.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/01419da9.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/04f60c28.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/04f60c28.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/0d69c7e1.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/0d69c7e1.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/10531352.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/10531352.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/111e6273.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/111e6273.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/12d55845.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/12d55845.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1ae85e5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1ae85e5e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1df5a75f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1df5a75f.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1e1eab7c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1e1eab7c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1e8e7201.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1e8e7201.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1eb37bdf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1eb37bdf.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/1f58a078.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/1f58a078.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/219d9499.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/219d9499.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/23f4c490.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/23f4c490.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/27af790d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/27af790d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/2add47b6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2add47b6.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/2d9dafe4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2d9dafe4.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/2fa87019.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/2fa87019.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/302904dd.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/302904dd.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/304d27c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/304d27c3.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/31188b5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/31188b5e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/33ee480d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/33ee480d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/343eb6cb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/343eb6cb.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/35105088.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/35105088.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/399e7759.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/399e7759.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3ad48a91.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3ad48a91.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3c6676aa.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c6676aa.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3c860d51.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c860d51.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3c899c73.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c899c73.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3c9a4d3b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3c9a4d3b.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/3e7271e8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/3e7271e8.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/40dc992e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/40dc992e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/455f1b52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/455f1b52.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/48a195d8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/48a195d8.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/4be590e0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/4be590e0.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5046c355.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5046c355.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/524d9b43.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/524d9b43.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/52b525c7.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/52b525c7.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/583d0756.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/583d0756.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5a250ea7.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5a250ea7.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5a3f0ff8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5a3f0ff8.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5acf816d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5acf816d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5cf9d536.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5cf9d536.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/5f47b495.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/5f47b495.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/60afe812.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/60afe812.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/6187b673.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/6187b673.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/63a2c897.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/63a2c897.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/69105f4f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/69105f4f.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/6b03dec0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/6b03dec0.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/75680d2e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/75680d2e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/76579174.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/76579174.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/7892ad52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7892ad52.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/7a7c655d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7a7c655d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/7a819ef2.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/7a819ef2.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/81b9768f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/81b9768f.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/82223c44.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/82223c44.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/83e9984f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/83e9984f.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/85cde254.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/85cde254.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/86212b19.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/86212b19.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/869fbf79.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/869fbf79.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/882de061.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/882de061.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/88950faa.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/88950faa.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/89c02a45.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/89c02a45.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/8d6437c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/8d6437c3.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9282e51c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9282e51c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9339512a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9339512a.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9479c8c3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9479c8c3.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9576d26b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9576d26b.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9591a472.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9591a472.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/95aff9e3.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/95aff9e3.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9685a493.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9685a493.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/985c1f52.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/985c1f52.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9aef356c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9aef356c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9d6523ce.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9d6523ce.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/9f533518.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/9f533518.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/a2c66da8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a2c66da8.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/a3896b44.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a3896b44.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/a7605362.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a7605362.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/a81e292b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a81e292b.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/a9d40e02.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/a9d40e02.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/ab5346f4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ab5346f4.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/ab59055e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ab59055e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/aeb67534.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/aeb67534.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b0ed035a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b0ed035a.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b0f3e76e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b0f3e76e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b3fb433b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b3fb433b.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b74d2bd5.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b74d2bd5.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b7db1890.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b7db1890.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b872f2b4.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b872f2b4.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/b936d1c6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/b936d1c6.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/bc3f2570.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bc3f2570.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/bd43e1dd.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bd43e1dd.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/bdacca6f.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bdacca6f.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/bf64f35b.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/bf64f35b.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/c491639e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c491639e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/c51c224c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c51c224c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/c559d742.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c559d742.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/c90bc37d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/c90bc37d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/cb1c3204.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/cb1c3204.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/ccc52f49.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ccc52f49.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/cf701eeb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/cf701eeb.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d06393bb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d06393bb.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d16a5865.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d16a5865.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d18e9066.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d18e9066.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d39b0a2c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d39b0a2c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d41b5e2a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d41b5e2a.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d4c339cb.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d4c339cb.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d59297b8.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d59297b8.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/d7746a63.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/d7746a63.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/da7377f6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/da7377f6.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/dbc54cab.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dbc54cab.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/dbff3a01.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dbff3a01.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/dc99f41e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dc99f41e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/dfc0fe80.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/dfc0fe80.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/e442e424.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e442e424.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/e48193cf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e48193cf.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/e8651083.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/e8651083.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/ed39abd0.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/ed39abd0.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/edcbddb5.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/edcbddb5.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/f013ecaf.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f013ecaf.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/f0cd152c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f0cd152c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/f459871d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/f459871d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/fb5fa911.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fb5fa911.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/fd08c599.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fd08c599.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts/fde84897.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts/fde84897.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/111e6273.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/111e6273.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/3ad48a91.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/3ad48a91.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/7651b327.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/7651b327.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/c542733d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/c542733d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/cec771d5.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/cec771d5.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/f336e3d1.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/f336e3d1.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/18dc3a8d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/18dc3a8d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/1bc5ca0c.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/1bc5ca0c.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/1bc5ca0c.1:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/1bc5ca0c.1 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/2cbfcc3a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/2cbfcc3a.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/35ef1c14.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/35ef1c14.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/399e7759.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/399e7759.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/586933d9.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/586933d9.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/66272d0d.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/66272d0d.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/6f1dbe5e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/6f1dbe5e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/b5805141.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/b5805141.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/b805b58a.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/b805b58a.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/ed7b215e.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/ed7b215e.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/security/cacerts_supl/lab/ef4b31e6.0:$(TARGET_COPY_OUT_VENDOR)/etc/security/cacerts_supl/lab/ef4b31e6.0 \
    vendor/xiaomi/ice/proprietary/vendor/etc/sensors/hals.conf:$(TARGET_COPY_OUT_VENDOR)/etc/sensors/hals.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/slp_conf:$(TARGET_COPY_OUT_VENDOR)/etc/slp_conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/smsdbvisitor.xml:$(TARGET_COPY_OUT_VENDOR)/etc/smsdbvisitor.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/special_pws_channel.xml:$(TARGET_COPY_OUT_VENDOR)/etc/special_pws_channel.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/spk_pb.wav:$(TARGET_COPY_OUT_VENDOR)/etc/spk_pb.wav \
    vendor/xiaomi/ice/proprietary/vendor/etc/task_profiles.json:$(TARGET_COPY_OUT_VENDOR)/etc/task_profiles.json \
    vendor/xiaomi/ice/proprietary/vendor/etc/throttle.sh:$(TARGET_COPY_OUT_VENDOR)/etc/throttle.sh \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/FTS_testdata.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/FTS_testdata.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/FTS_testresult.txt:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/FTS_testresult.txt \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/FWCCTest.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/FWCCTest.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/FWRawdataTest.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/FWRawdataTest.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/NoiseTest.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/NoiseTest.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/OpenTest.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/OpenTest.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/touchpad/ShortTest.csv:$(TARGET_COPY_OUT_VENDOR)/etc/touchpad/ShortTest.csv \
    vendor/xiaomi/ice/proprietary/vendor/etc/ueventd.rc:$(TARGET_COPY_OUT_VENDOR)/etc/ueventd.rc \
    vendor/xiaomi/ice/proprietary/vendor/etc/usb_audio_accessory_only_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_accessory_only_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/usb_audio_policy_configuration.xml:$(TARGET_COPY_OUT_VENDOR)/etc/usb_audio_policy_configuration.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/vendor-apns-conf.xml:$(TARGET_COPY_OUT_VENDOR)/etc/vendor-apns-conf.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/virtual-spn-conf-by-efgid1.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efgid1.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/virtual-spn-conf-by-efpnn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efpnn.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/virtual-spn-conf-by-efspn.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-efspn.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/virtual-spn-conf-by-imsi.xml:$(TARGET_COPY_OUT_VENDOR)/etc/virtual-spn-conf-by-imsi.xml \
    vendor/xiaomi/ice/proprietary/vendor/etc/wifi/p2p_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/p2p_supplicant_overlay.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/wifi/wpa_supplicant.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant.conf \
    vendor/xiaomi/ice/proprietary/vendor/etc/wifi/wpa_supplicant_overlay.conf:$(TARGET_COPY_OUT_VENDOR)/etc/wifi/wpa_supplicant_overlay.conf \
    vendor/xiaomi/ice/proprietary/vendor/firmware/BT_FW.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/BT_FW.cfg \
    vendor/xiaomi/ice/proprietary/vendor/firmware/Conf_MultipleTest.ini:$(TARGET_COPY_OUT_VENDOR)/firmware/Conf_MultipleTest.ini \
    vendor/xiaomi/ice/proprietary/vendor/firmware/ICNL9916.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/ICNL9916.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/WIFI_RAM_CODE_soc1_0_1_1.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/WIFI_RAM_CODE_soc1_0_1_1.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/WMT_SOC.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/WMT_SOC.cfg \
    vendor/xiaomi/ice/proprietary/vendor/firmware/aw87389_monitor.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87389_monitor.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/aw87xxx_acf.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/aw87xxx_acf.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/awinic_params.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/awinic_params_mute.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/awinic_params_mute.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/fm_cust.cfg:$(TARGET_COPY_OUT_VENDOR)/firmware/fm_cust.cfg \
    vendor/xiaomi/ice/proprietary/vendor/firmware/focaltech_ts_fw_helitai.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/focaltech_ts_fw_helitai.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/fs1599.fsm:$(TARGET_COPY_OUT_VENDOR)/firmware/fs1599.fsm \
    vendor/xiaomi/ice/proprietary/vendor/firmware/gt1151_default_firmware2.img:$(TARGET_COPY_OUT_VENDOR)/firmware/gt1151_default_firmware2.img \
    vendor/xiaomi/ice/proprietary/vendor/firmware/mt6631_fm_v1_coeff.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_coeff.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/mt6631_fm_v1_patch.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/mt6631_fm_v1_patch.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/novatek_ts_truly_fw.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_truly_fw.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/novatek_ts_truly_mp.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/novatek_ts_truly_mp.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/remoteproc_scp:$(TARGET_COPY_OUT_VENDOR)/firmware/remoteproc_scp \
    vendor/xiaomi/ice/proprietary/vendor/firmware/rgx.fw:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.fw \
    vendor/xiaomi/ice/proprietary/vendor/firmware/rgx.sh:$(TARGET_COPY_OUT_VENDOR)/firmware/rgx.sh \
    vendor/xiaomi/ice/proprietary/vendor/firmware/soc1_0_patch_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_patch_mcu_1_1_hdr.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/soc1_0_ram_bt_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_bt_1_1_hdr.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/soc1_0_ram_mcu_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_mcu_1_1_hdr.bin \
    vendor/xiaomi/ice/proprietary/vendor/firmware/soc1_0_ram_wifi_1_1_hdr.bin:$(TARGET_COPY_OUT_VENDOR)/firmware/soc1_0_ram_wifi_1_1_hdr.bin \
    vendor/xiaomi/ice/proprietary/vendor/lib/egl/egl.cfg:$(TARGET_COPY_OUT_VENDOR)/lib/egl/egl.cfg \
    vendor/xiaomi/ice/proprietary/vendor/lib/mibokeh_mt6768_opencl.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_mt6768_opencl.bin \
    vendor/xiaomi/ice/proprietary/vendor/lib/mibokeh_mt6768_parameter.bin:$(TARGET_COPY_OUT_VENDOR)/lib/mibokeh_mt6768_parameter.bin \
    vendor/xiaomi/ice/proprietary/vendor/lib/modules/modules.alias:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.alias \
    vendor/xiaomi/ice/proprietary/vendor/lib/modules/modules.dep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.dep \
    vendor/xiaomi/ice/proprietary/vendor/lib/modules/modules.load:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.load \
    vendor/xiaomi/ice/proprietary/vendor/lib/modules/modules.softdep:$(TARGET_COPY_OUT_VENDOR)/lib/modules/modules.softdep \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/0102030405060708090a0b0c0d0e0f10.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/0102030405060708090a0b0c0d0e0f10.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/511ead0a000000000000000000000000.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/511ead0a000000000000000000000000.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/7778c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/86f623f6a2994dfdb560ffd3e5a62c29.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/8888c03fc30c4dd0a319ea29643d4d4b.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/93feffccd8ca11e796c7c7a21acb4932.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c09c9c5daa504b78b0e46eda61556c3a.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/c1882f2d885e4e13a8c8e2622461b2fa.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d78d338b1ac349e09f65f4efe179739d.ta \
    vendor/xiaomi/ice/proprietary/vendor/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta:$(TARGET_COPY_OUT_VENDOR)/thh/ta/d91f322ad5a441d5955110eda3272fc0.ta \

PRODUCT_PACKAGES += \
    GoogleNetworkStackResOverlay \
    GoogleTetheringResOverlay \
    InProcessTetheringResOverlay \
    NetworkStackInProcessResOverlay \
    NetworkStackResOverlay \
    TetheringResOverlay \
    com.fingerprints.extension \
    android.hardware.dumpstate@1.1-service.xiaomi \
    android.hardware.wifi.hostapd \
    android.hardware.wifi.supplicant \
    android.hardware.wifi@1.0-service \
    gnss-default \
    gnss@2.1-service \
    lbs_hidl_service@1.0 \
    lights-mtk-default \
    manifest_android.hardware.drm@1.4-service.clearkey \
    manifest_hwcomposer \
    manifest_vendor.xiaomi.hardware.mtdservice \
    power-default \
    vibrator-mtk-default

PRODUCT_COPY_FILES += \

PRODUCT_PACKAGES += ImsService

PRODUCT_PACKAGES += doeapp-memtester

PRODUCT_PACKAGES += \
    AgentTest \
    SoterProvisioningTool \
    aee_aedv \
    aee_dumpstatev \
    aeev \
    atcid \
    audiocmdservice_atci \
    bip \
    ccci_mdinit \
    charge_logger \
    bp_kmsetkey_ca \
    em_hidl \
    ccci_rpcd \
    dtc_vendor \
    factory \
    autobt \
    dconfig \
    dmc_core \
    cal_tool \
    dexecutor \
    epdg_wod \
    fuelgauged \
    hostapd_cli \
    atci_service \
    doeapp-sat \
    android.hardware.bluetooth@1.1-service-mediatek \
    android.hardware.graphics.allocator@4.0-service-mediatek \
    android.hardware.keymaster@4.1-service.beanpod \
    android.hardware.audio.service.mediatek \
    android.hardware.lights-service.mediatek

PRODUCT_PACKAGES += \
    charon \
    jpegtool \
    loghidlvendorservice \
    kmsetkey \
    ipsec_mon \
    md_monitor_ctrl \
    mnld \
    md_monitor \
    android.hardware.drm@1.4-service-lazy.widevine \
    android.hardware.media.c2@1.2-mediatek \
    android.hardware.sensors@2.0-service.multihal-mediatek \
    android.hardware.vibrator-service.mediatek \
    camerahalserver \
    hostapd \
    merged_hal_service \
    mtkfusionrild \
    vendor.mediatek.hardware.aee@1.1-service \
    vendor.mediatek.hardware.keymaster_attestation@1.1-service \
    vendor.mediatek.hardware.mtkpower@1.0-service \
    vendor.mediatek.hardware.mmagent@1.1-service \
    vendor.mediatek.hardware.nvram@1.1-service-lazy \
    vendor.mediatek.hardware.pq@2.2-service \
    vendor.xiaomi.hardware.misys@1.0-service \
    vendor.xiaomi.hardware.misys@2.0-service \
    vendor.xiaomi.hardware.misys@3.0-service \
    vendor.silead.hardware.fingerprintext@1.0-service \
    wpa_supplicant \
    vendor.mediatek.hardware.mms@1.6-service \
    vtservice_hidl

PRODUCT_PACKAGES += \
    gsm0710muxd \
    meta_tst \
    mrdump_tool \
    mtd@1.2 \
    mtk_agpsd \
    mtk_pkm_service \
    mtk_plpath_utils_ota \
    muxreport \
    netdagent \
    netdc \
    nv_routing \
    mt6660_calibration \
    pvrhwperfd \
    rcs_volte_stack \
    rt5512_calibration \
    rttv \
    sensors_test \
    starter \
    stp_dump3 \
    stroke

PRODUCT_PACKAGES += \
    teei_daemon \
    thermal \
    thermal_manager \
    thermalloadalgod \
    volte_imsm_93 \
    volte_md_status \
    volte_rcs_ua \
    volte_stack \
    volte_ua \
    wfca \
    volte_imcb \
    wmt_launcher \
    wlan_assistant \
    wmt_loader \
    wpa_cli

PRODUCT_PACKAGES += \
    libcam.halisp \
    libcamalgo.fsc \
    libSonyIMX386PdafLibraryWrapper \
    libudf \
    libminiui \
    libcodec2_mtk_c2store \
    libcharon-ss \
    vendor.mediatek.hardware.pq@2.8 \
    vendor.mediatek.hardware.pq@2.9 \
    libpqparamparser \
    vendor.mediatek.hardware.pq@2.11 \
    libteei_daemon_vfs \
    libbessound_hd_mtk_vendor \
    libsimmelock \
    vendor.mediatek.hardware.camera.postproc@1.0 \
    libSonyIMX386PdafLibrary \
    libforkexecwrap \
    vendor.xiaomi.hardware.mtdservice@1.1 \
    libusc \
    libmemtrack_GL \
    libcodec2_soft_mtk_imaadpcmdec \
    libbluetooth_audio_session_mediatek \
    libheichal \
    vendor.mediatek.hardware.nvram@1.1 \
    libcamalgo.utility \
    libmtkcam_3rdparty.customer \
    libaurisysdemo \
    libhwm \
    libstrongswan \
    libmnetlink_v104 \
    vendor.mediatek.hardware.engineermode@1.1 \
    libaalservice \
    libcam.feature_utils \
    libmtkmipc-ril \
    sc_sc800cs_india_ii_IdxMgr \
    libion_mtk \
    libsl_fp_impl \
    libmsnr \
    libmtkcam_imgbuf \
    libcamdrv_tuning_mgr \
    libasn1c_mdmi \
    libmtk-fusion-ril-prop-vsim \
    vendor.mediatek.hardware.power@2.0 \
    libmnl \
    libmtkcam_imem \
    libcomposer_ext \
    libthermalalgo \
    libmtkcam_pipelinepolicy-aov \
    libmtkcam_ulog \
    vendor.mediatek.hardware.keymaster_attestation@1.1 \
    libMtkSpeechEnh \
    libksensor \
    libvt_custom \
    libmtkcam_fdvt \
    libaudiofmtconv \
    libnvram_sec \
    libcam.utils.sensorprovider \
    vendor.mediatek.hardware.engineermode@1.3 \
    libarcsoft_hdr_detection \
    libvolte_xdmc_shr \
    vendor.mediatek.hardware.dmc@1.1 \
    libSonyIMX338PdafLibraryWrapper \
    libfeature_lmv \
    libbluetooth_mtk \
    libcamalgo.gyro \
    libmmagent \
    libmtksysutils \
    libratconfig \
    libnxp_extamp_intf \
    sams_s5k5e9_india_i_tuning \
    libmtkcam_rsc \
    libTEECommon \
    libcodec2_vpp_rs_plugin \
    libspeechparser_vendor \
    libpqframework \
    libconnfem \
    libfeature.stereo.provider \
    libcodec2_mtk_vdec \
    libbluetooth_hw_test \
    libvcodec_utility \
    libmtkrilutils \
    libcamalgo.dngop \
    libgpud \
    libasn1c_core \
    vendor.mediatek.hardware.netdagent@1.0 \
    libmtkcam_3rdparty.core \
    libwpfa \
    liblogwrap_vendor \
    libimageio_plat_pipe \
    libcodec2_soft_mtk_alacdec \
    libcamalgo.platform \
    com.fingerprints.extension@1.0 \
    libmtkcam_pipelinemodel_adapter \
    libstorage_otp \
    libfgauge_gm30 \
    libmtkshifter_vendor \
    vendor.mediatek.hardware.audio@6.1 \
    sc_sc500cs_ii_IdxMgr \
    libmtkcam_pipelinemodel_session \
    libmtkcam.eventcallback \
    vendor.mediatek.hardware.pq@2.4 \
    libcheckpid \
    sams_s5k4h7_iii_IdxMgr \
    sams_s5k5e9_india_iii_IdxMgr \
    libnvram \
    vendor.mediatek.hardware.mtkradioex@3.0 \
    libmtktinyxml \
    libcamalgo.nr \
    libkmsetkey \
    sams_s5k5e9_i_IdxMgr \
    libformatter \
    vendor.mediatek.hardware.mms@1.6 \
    librilfusion \
    libfeature_rss \
    vendor.mediatek.hardware.apmonitor@2.0 \
    vendor.mediatek.hardware.videotelephony@1.0 \
    vendor.xiaomi.hardware.mtdservice@1.0 \
    libmtkcam_exif \
    libmtkcam_device3_hidl \
    libpq_prot \
    libvp8dec_sa.ca7 \
    libPVRScopeServices \
    vendor.silead.hardware.fingerprintext@1.0 \
    libSQLiteModule_VER_ALL \
    sams_s5k4h7_iii_tuning \
    libmtkcam_diputils \
    libarcsoft_high_dynamic_range \
    libvp9dec_sa.ca7 \
    sc_sc500cs_india_ii_tuning \
    libssl-mdapp \
    wechat.beanpod \
    libSonyIMX519PdafLibrary \
    libmtkcam.atmseventmgr \
    libcamalgo.eis \
    libtqvalidate \
    libmtkcam_device3_utils \
    libmtkcam_3rdparty \
    libmtkcam_pipeline_fbm \
    libapu_mdw \
    libmtkcam.featurepipe.capture \
    libcodec2_soft_mtk_apedec \
    sc_sc800cs_ii_IdxMgr \
    lib3a.af.core \
    libmtkspparser \
    libgf_hal \
    vendor.mediatek.hardware.mms@1.5 \
    libmtkcam_pipelinemodel_capture \
    libmtkcam_pipeline \
    libmtkconfig \
    libvpu5 \
    sams_s5k5e9_iii_tuning \
    sams_s5k4h7_india_i_tuning \
    vendor.mediatek.hardware.mms@1.4 \
    libtranslator_utils \
    libneuropilot_hal_utils \
    libgralloc_metadata \
    libgpu_aux \
    libvia-ril \
    libaudio_param_parser-vnd \
    audio_common-aidl-cpp \
    libmtkcam_device3_hidlutils \
    libfeatureiodrv_mem \
    libcam.vhdr \
    libmtkcam_pipelinepolicy \
    vendor.xiaomi.hardware.misys@3.0 \
    libmp3dec_mtk \
    vendor.mediatek.hardware.pq@2.2 \
    libmtkcam_metastore \
    libcam.pdtblgen \
    libgf_ca \
    vendor.mediatek.hardware.pq@2.7 \
    libJpgEncPipe \
    libmtkares \
    meta_wifi_data \
    libmtkrillog \
    vendor.mediatek.hardware.pq@2.12 \
    libcamalgo.ispfeature \
    libmml \
    libmp4enc_xa.ca7 \
    libmtkcam_grallocutils \
    libmibokeh_mt6768 \
    libmtkcam_pipelinepolicy_factory \
    libbluetooth_relayer \
    vendor.mediatek.hardware.audio@7.1 \
    libpqpconfig \
    lib_speech_enh \
    libmtkconfigutils \
    libgralloctypes_mtk \
    vendor.mediatek.hardware.camera.security@1.0 \
    libhevce_sb.ca7.android \
    libsimlock \
    libh264dec_sa.ca7 \
    libvcodec_oal \
    libh264dec_sd.ca7 \
    lib3a.log \
    libcamalgo.platform2 \
    libvcodecdrv_header_stub \
    libcam.halsensor \
    libvendor.goodix.hardware.biometrics.fingerprint@2.1 \
    libimsg_log \
    libmtk-ril \
    libaudiocompensationfilter_vendor \
    vendor.mediatek.hardware.camera.frhandler@1.0 \
    libdecrypt \
    libmtkutils \
    android.hardware.vibrator-V2-ndk \
    libcamalgo.lmv \
    libIMGegl \
    libmipc \
    libaudiocomponentengine_vendor \
    libwo \
    libacdk \
    libcamalgo.3dnr \
    vendor.mediatek.hardware.camera.isphal@1.1 \
    lib3a.ae \
    libcam.chdr \
    libSonyIMX338PdafLibrary \
    vendor.mediatek.hardware.dmc@1.2 \
    libPVROCL \
    libmtkcam_calibration_provider \
    libfeature.face \
    lib3a.awb.core \
    libaudioprimarydevicehalifclient \
    libhydra \
    libperfctl_vendor \
    libmtkcutils \
    libfeature_fsc \
    vendor.mediatek.hardware.pq@2.13 \
    vendor.mediatek.hardware.pq@2.5 \
    libcam.hal3a.v3.lsctbl \
    libimageio \
    libmmprofile \
    vendor.xiaomi.hardware.mtdservice@1.2 \
    libarcsoft_low_light_hdr \
    libviamipc-ril \
    libbt-vendor \
    libh264dec_customize \
    libmtcloader \
    ov02b_mipi_raw_tuning \
    libmtk_drvb \
    libcvsd_mtk \
    libHEVCdec_sa.ca7.android \
    libmtknetcap \
    libmtkcam_3rdparty.mtk \
    libcodec2_soft_mtk_mp3dec \
    libcurl_xcap_md \
    libblisrc32_vendor \
    libcam.hal3a.v3.dng \
    libmtkcam.logicalmodule \
    libapmonitor_vendor \
    libaudiotoolkit_vendor \
    libh264dec_se.ca7 \
    libsensor_custom \
    libaudiocomponentenginec \
    libmtkcam_modulefactory_custom \
    libpower_timer \
    libcrypto-mdapp \
    vendor.mediatek.hardware.lbs@1.0 \
    libmtkcam_debugutils \
    libmtkcam.featurepipe.vsdof_util \
    sams_s5k4h7_i_tuning \
    libmtkcam_featureutils \
    libthha \
    libimageio_plat_drv \
    vendor.mediatek.hardware.pq@2.14 \
    vendor.mediatek.hardware.nvram@1.0 \
    libmtkcam_modulefactory_drv \
    libaal_cust \
    sams_s5k5e9_india_iii_tuning \
    libcurl-md \
    libmtkcam_scenariorecorder \
    libcamalgo \
    libmtkcam_calibration_convertor \
    lib3a.af \
    vendor.mediatek.hardware.composer_ext@1.0 \
    sams_s5k5e9_i_tuning \
    vendor.mediatek.hardware.pq@2.6 \
    libcarrierconfig \
    libmtkcam.featurepipe.streaming \
    vendor.xiaomi.hardware.misys@2.0 \
    libmtkcam_hwnode \
    libmt@1.2 \
    libmtkcam_tuning_utils \
    libcam.hal3a.v3.nvram \
    sams_s5k4h7_india_iii_tuning \
    vendor.mediatek.hardware.camera.isphal@1.0 \
    libpixelflinger \
    libcam.hal3a.cctsvr \
    libstagefrighthw \
    liblpcnr \
    libpowerhal \
    lib_lowlight \
    sams_s5k4h7_india_i_IdxMgr \
    libadpcmdec_mtk \
    vendor.mediatek.hardware.pq@2.15 \
    libcam3a_imem \
    vendor.mediatek.hardware.pq@2.1 \
    vendor.mediatek.hardware.atci@1.0 \
    libSonyIMX519PdafLibraryWrapper \
    libdynamiclog \
    vendor.mediatek.hardware.bluetooth.audio@2.1 \
    libaudioloudc \
    vendor.mediatek.hardware.bluetooth.audio@2.2 \
    libverno \
    libaal_key \
    libmtkcam_hwutils \
    libmtkcam_modulefactory_aaa \
    vendor.mediatek.hardware.mmagent@1.0 \
    libwapi \
    libcam.hal3a.v3 \
    libmtklimiter_vendor \
    vendor.mediatek.hardware.aee@1.1 \
    vendor.mediatek.hardware.engineermode@1.2 \
    vendor.mediatek.hardware.rcs@2.0 \
    libtranslator_mapi_v3.0 \
    sams_s5k4h7_india_iii_IdxMgr \
    vendor.mediatek.hardware.aee@1.0 \
    libmtkproperty \
    libPVRMtkutils \
    libmtkcam_fwkutils \
    libion_ulit \
    libmtkcam_device3_hal \
    libgralloc_extra \
    libbluetooth_mtk_pure \
    libpowerhalwrap_vendor \
    libaudiocompensationfilterc \
    libDefaultFpsActor \
    libmtkcam_pipelinemodel \
    libmtkcam_featurepolicy \
    libmtkcam_streamutils \
    libwpa_client \
    libSonyIMX230PdafLibrary \
    libutinterface_custom_md \
    librt_extamp_intf \
    libcustom_nvram \
    vendor.mediatek.hardware.pq@2.3 \
    vendor.mediatek.hardware.log@1.0 \
    libbwc \
    vendor.mediatek.hardware.keymaster_attestation@1.0 \
    libcam.iopipe \
    libfft_vendor \
    libcamalgo.warp \
    libmtkcam_modulehelper \
    libmtkcam_synchelper \
    sc_sc800cs_india_ii_tuning \
    libmtkcam_stdutils \
    libglslcompiler \
    vendor.mediatek.hardware.mms@1.0 \
    vendor.mediatek.hardware.mtkpower@1.1 \
    libeffecthal.base \
    vendor.mediatek.hardware.camera.lomoeffect@1.0 \
    libapusys \
    libcamdrv \
    libpq_cust_base \
    sams_s5k4h7_i_IdxMgr \
    libpkm \
    sensors.camera.light \
    libspeech_enh_lib \
    sc_sc500cs_ii_tuning \
    libcamalgo.flicker \
    libvolte_core_shr \
    libarcsoft_beautyshot \
    libcamalgo.fdft \
    libjpeg-alpha-oal_vendor \
    vendor.mediatek.hardware.camera.ccap@1.0 \
    libicd_decoder \
    libmsbc_mtk \
    sams_s5k5e9_iii_IdxMgr \
    libcodec2_soft_mtk_msadpcmdec \
    libmtknetutils \
    libsysenv \
    libmtkcam_pipelinemodel_utils \
    lbs_hidl_service-impl \
    ov02b_mipi_raw_IdxMgr \
    librcs_volte_core \
    lib3a.ae.core \
    libOpenCL \
    libcamalgo.lsc \
    libsrv_um \
    libnvramagentclient \
    libmtkcam_sysutils \
    libmtkcam_modulefactory_utils \
    vendor.mediatek.hardware.mms@1.1 \
    sams_s5k5e9_india_i_IdxMgr \
    libDR \
    libutinterface_md \
    vendor.mediatek.hardware.pq@2.10 \
    libFrameRecord \
    libufwriter \
    libNoFpsActor \
    libbluetoothem_mtk \
    sc_sc500cs_india_ii_IdxMgr \
    libfeature_3dnr \
    libmtkcam_prerelease \
    sc_sc800cs_ii_tuning \
    libmpvr \
    libh264enc_sa.ca7 \
    libapusys_edma \
    libmtkcam_metadata \
    libmtkcam_devicesessionpolicy \
    lib3a.flash \
    vendor.xiaomi.hardware.misys@1.0 \
    lib3a.awb \
    libstereoinfoaccessor_vsdof \
    vendor.mediatek.hardware.pq@2.0 \
    libMtkOmxGsmDec \
    libipsec_ims_shr \
    libSonyIMX230PdafLibraryWrapper \
    libmtkcam_device3_app \
    libasn1c_mapi \
    libaudiocustparam_vendor \
    libmtkperf_client_vendor \
    libwvhidl \
    vendor.mediatek.hardware.mms@1.3 \
    libcam.hal3a.log \
    vendor.mediatek.hardware.engineermode@1.0 \
    vendor.mediatek.hardware.mmagent@1.1 \
    libmp4enc_sa.ca7 \
    libmtkhardware_legacy \
    libged \
    libmtkcam_pipelinepolicy-security \
    libtranslator_mdmi_v2.8.2 \
    libcares_naptr \
    libjpeg-alpha_vendor \
    vendor.mediatek.hardware.mdmonitor@1.0 \
    librcs_interface \
    libwifitest \
    libtrm \
    libladder \
    libaudiodcrflt_vendor \
    vendor.mediatek.hardware.camera.atms@1.0 \
    libcodec2_vpp_qt_plugin \
    libcodec2_mtk_venc \
    libmtkcam_pipelinemodel_zsl \
    libaal_mtk \
    libcameracustom \
    android.hardware.power-service-mediatek \
    libMtkOmxMp3Dec \
    libccci_util \
    vendor.mediatek.hardware.dmc@1.0 \
    vendor.mediatek.hardware.mtkpower@1.0 \
    libfile_op \
    vendor.mediatek.hardware.mms@1.2 \
    libvcodecdrv \
    libgoodixhwfingerprint \
    libmtk_bsg \
    libMtkOmxCore \
    libmtkcam_pipelinepolicy-smvr \
    libifcutils_mtk \
    lib_iir \
    libdpframework \
    libsimaka \
    libmpbase \
    vendor.mediatek.hardware.mtkpower@1.2 \
    librgbwlightsensor \
    libaedv \
    libpq_prot \
    libmtk_drvb \
    libdpframework \
    libmockdrmcryptoplugin \
    libwvdrmengine \
    libMEOW_qt \
    libGLESv2_mtk \
    libMEOW_trace \
    libMEOW_gift \
    libGLES_meow \
    libEGL_mtk \
    libGLESv1_CM_mtk \
    lights.mt6761 \
    fingerprint.fpc.default \
    vendor.mediatek.hardware.camera.lomoeffect@1.0-impl \
    vendor.xiaomi.hardware.misys@3.0-impl \
    android.hardware.gnss@2.1-impl-mediatek \
    android.hardware.bluetooth@1.1-impl-mediatek \
    vibrator.mt6761 \
    vendor.mediatek.hardware.bluetooth.audio@2.1-impl \
    vendor.mediatek.hardware.pq@2.15-impl \
    android.hardware.audio@6.0-impl-mediatek \
    libSoftGatekeeper \
    android.hardware.thermal@2.0-impl \
    awinic.audio.effect \
    android.hardware.graphics.mapper@4.0-impl-mediatek \
    vendor.mediatek.hardware.camera.atms@1.0-impl \
    gralloc.rogue \
    vendor.mediatek.hardware.bluetooth.audio@2.2-impl \
    audio.r_submix.mt6761 \
    kmsetkey.beanpod \
    memtrack.default \
    hwcomposer.mt6761 \
    gatekeeper.default \
    fingerprint.goodix.default \
    vendor.mediatek.hardware.keymaster_attestation@1.1-impl \
    android.hardware.boot@1.0-impl-1.2-mtkimpl \
    audio.primary.mt6761 \
    fingerprint.silead.default \
    android.hardware.sensors@2.X-subhal-mediatek \
    vendor.xiaomi.hardware.misys@2.0-impl \
    gps.default \
    vendor.mediatek.hardware.mtkpower@1.2-impl \
    vendor.mediatek.hardware.mms@1.6-impl \
    vendor.xiaomi.hardware.misys@1.0-impl \
    sensors.mt6761 \
    vendor.mediatek.hardware.videotelephony@1.0-impl \
    android.hardware.audio@7.0-impl-mediatek \
    android.hardware.gnss-impl-mediatek \
    android.hardware.camera.provider@2.6-impl-mediatek \
    vendor.mediatek.hardware.nvram@1.1-impl \
    gatekeeper.beanpod \
    thermal_hal \
    libaudiopreprocessing_mtk

PRODUCT_PACKAGES += libmockdrmcryptoplugin

PRODUCT_PACKAGES += libwvdrmengine

PRODUCT_PACKAGES += libMEOW_qt

PRODUCT_PACKAGES += libGLESv2_mtk

PRODUCT_PACKAGES += libMEOW_trace

PRODUCT_PACKAGES += libMEOW_gift

PRODUCT_PACKAGES += libGLES_meow

PRODUCT_PACKAGES += libEGL_mtk

PRODUCT_PACKAGES += libGLESv1_CM_mtk

PRODUCT_PACKAGES += lights.mt6761

PRODUCT_PACKAGES += fingerprint.fpc.default

PRODUCT_PACKAGES += vendor.mediatek.hardware.camera.lomoeffect@1.0-impl

PRODUCT_PACKAGES += vendor.xiaomi.hardware.misys@3.0-impl

PRODUCT_PACKAGES += android.hardware.gnss@2.1-impl-mediatek

PRODUCT_PACKAGES += android.hardware.bluetooth@1.1-impl-mediatek

PRODUCT_PACKAGES += vibrator.mt6761

PRODUCT_PACKAGES += vendor.mediatek.hardware.bluetooth.audio@2.1-impl

PRODUCT_PACKAGES += vendor.mediatek.hardware.pq@2.15-impl

PRODUCT_PACKAGES += android.hardware.audio@6.0-impl-mediatek

PRODUCT_PACKAGES += libSoftGatekeeper

PRODUCT_PACKAGES += android.hardware.thermal@2.0-impl

PRODUCT_PACKAGES += awinic.audio.effect

PRODUCT_PACKAGES += android.hardware.graphics.mapper@4.0-impl-mediatek

PRODUCT_PACKAGES += vendor.mediatek.hardware.camera.atms@1.0-impl

PRODUCT_PACKAGES += gralloc.rogue

PRODUCT_PACKAGES += vendor.mediatek.hardware.bluetooth.audio@2.2-impl

PRODUCT_PACKAGES += audio.r_submix.mt6761

PRODUCT_PACKAGES += kmsetkey.beanpod

PRODUCT_PACKAGES += memtrack.default

PRODUCT_PACKAGES += hwcomposer.mt6761

PRODUCT_PACKAGES += gatekeeper.default

PRODUCT_PACKAGES += fingerprint.goodix.default

PRODUCT_PACKAGES += vendor.mediatek.hardware.keymaster_attestation@1.1-impl

PRODUCT_PACKAGES += android.hardware.boot@1.0-impl-1.2-mtkimpl

PRODUCT_PACKAGES += audio.primary.mt6761

PRODUCT_PACKAGES += fingerprint.silead.default

PRODUCT_PACKAGES += android.hardware.sensors@2.X-subhal-mediatek

PRODUCT_PACKAGES += vendor.xiaomi.hardware.misys@2.0-impl

PRODUCT_PACKAGES += gps.default

PRODUCT_PACKAGES += vendor.mediatek.hardware.mtkpower@1.2-impl

PRODUCT_PACKAGES += vendor.mediatek.hardware.mms@1.6-impl

PRODUCT_PACKAGES += vendor.xiaomi.hardware.misys@1.0-impl

PRODUCT_PACKAGES += sensors.mt6761

PRODUCT_PACKAGES += vendor.mediatek.hardware.videotelephony@1.0-impl

PRODUCT_PACKAGES += android.hardware.audio@7.0-impl-mediatek

PRODUCT_PACKAGES += android.hardware.gnss-impl-mediatek

PRODUCT_PACKAGES += android.hardware.camera.provider@2.6-impl-mediatek

PRODUCT_PACKAGES += vendor.mediatek.hardware.nvram@1.1-impl

PRODUCT_PACKAGES += gatekeeper.beanpod

PRODUCT_PACKAGES += thermal_hal

PRODUCT_PACKAGES += libaudiopreprocessing_mtk

PRODUCT_PACKAGES += libsimaka

PRODUCT_PACKAGES += libmpbase

PRODUCT_PACKAGES += vendor.mediatek.hardware.mtkpower@1.2

PRODUCT_PACKAGES += librgbwlightsensor

PRODUCT_PACKAGES += libaedv

PRODUCT_PACKAGES += \
    wmt_drv.ko

PRODUCT_PACKAGES += mi_memory.ko

PRODUCT_PACKAGES += wmt_chrdev_wifi.ko

PRODUCT_PACKAGES += wlan_drv_gen4m.ko

PRODUCT_PACKAGES += fpsgo.ko

PRODUCT_PACKAGES += fmradio_drv_mt6631.ko

PRODUCT_PACKAGES += mt6357-accdet.ko

PRODUCT_PACKAGES += trace_mmstat.ko

PRODUCT_PACKAGES += bt_drv_connac1x.ko

PRODUCT_PACKAGES += met.ko

PRODUCT_PACKAGES += connfem.ko

PRODUCT_PACKAGES += gps_drv.ko
